import { FC } from 'react';

import Head from 'next/head';
import { Navbar } from '../ui';
import Script from 'next/script';

interface Props {
  title?: string;
  children:
  | React.ReactChild
  | React.ReactChild[];
}


export const Layout: FC<Props> = ({ children, title }) => {
  return (
      <>
        <Head>
          <title>Social Media Kit</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />

          <link href="https://fonts.googleapis.com/css2?family=Jura:wght@500;600;700&family=Krona+One&display=swap" rel="stylesheet"></link>
          
      </Head>

        <Navbar />

        <main style={{
          padding: '0px 20px'
        }}>

            { children }
        </main>

        <Script src="https://js.stripe.com/v3/" strategy="lazyOnload"></Script>
      </>
  )
};
